[13/Sep/2019 20:06:40] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:06:41] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:07:32] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:07:33] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:08:38] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:08:40] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:09:21] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:09:23] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:10:03] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:10:05] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:10:42] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:10:43] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1:8000'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
[13/Sep/2019 20:13:23] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:13:23] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:13:26] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:14:35] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:14:37] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:15:24] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:15:25] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:15:56] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:15:57] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: 'lucasfranciscocorreia.me'. You may need to add 'lucasfranciscocorreia.me' to ALLOWED_HOSTS.
[13/Sep/2019 20:17:26] ERROR [/home/lfpgc1996/.local/lib/python3.7/site-packages/django/core/handlers/exception.py:77] Invalid HTTP_HOST header: '34.66.250.1'. You may need to add '34.66.250.1' to ALLOWED_HOSTS.
